name: Development Build

on:
  workflow_dispatch:
    inputs:
      pg_version:
        description: 'PostgreSQL version to build'
        required: true
        default: '17'
        type: choice
        options:
          - '12'
          - '13' 
          - '14'
          - '15'
          - '16'
          - '17'
      create_artifacts:
        description: 'Create build artifacts'
        type: boolean
        default: true

jobs:
  dev-build:
    name: Development Build PG${{ github.event.inputs.pg_version }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set PostgreSQL image
      id: set_image
      run: |
        case "${{ github.event.inputs.pg_version }}" in
          12) echo "image=postgres:12-alpine3.17" >> $GITHUB_OUTPUT ;;
          13) echo "image=postgres:13-alpine3.17" >> $GITHUB_OUTPUT ;;
          14) echo "image=postgres:14-alpine3.18" >> $GITHUB_OUTPUT ;;
          15) echo "image=postgres:15-alpine3.19" >> $GITHUB_OUTPUT ;;
          16) echo "image=postgres:16-alpine3.20" >> $GITHUB_OUTPUT ;;
          17) echo "image=postgres:17-alpine3.20" >> $GITHUB_OUTPUT ;;
          *) echo "image=postgres:17-alpine3.20" >> $GITHUB_OUTPUT ;;
        esac

    - name: Quick test PostgreSQL ${{ github.event.inputs.pg_version }}
      run: |
        # Create test container
        docker run --name test_pg${{ github.event.inputs.pg_version }} -d \
          -e POSTGRES_PASSWORD=postgres \
          ${{ steps.set_image.outputs.image }}
        
        # Wait for PostgreSQL
        sleep 10
        
        # Install dependencies and build
        docker exec test_pg${{ github.event.inputs.pg_version }} apk add --no-cache \
          gcc musl-dev make postgresql${{ github.event.inputs.pg_version }}-dev
        
        docker cp . test_pg${{ github.event.inputs.pg_version }}:/src/
        docker exec test_pg${{ github.event.inputs.pg_version }} sh -c "cd /src && make clean && make install"
        
        # Quick test
        docker exec test_pg${{ github.event.inputs.pg_version }} psql -U postgres -c "CREATE EXTENSION jsonb_merge;"
        docker exec test_pg${{ github.event.inputs.pg_version }} psql -U postgres -c "SELECT jsonb_merge('{\"a\": 1}', '{\"b\": 2}');"

    - name: Create artifact
      if: github.event.inputs.create_artifacts == 'true'
      run: |
        mkdir -p dev-build/pg${{ github.event.inputs.pg_version }}
        docker cp test_pg${{ github.event.inputs.pg_version }}:/src/jsonb_merge.so dev-build/pg${{ github.event.inputs.pg_version }}/
        docker cp test_pg${{ github.event.inputs.pg_version }}:/src/jsonb_merge.control dev-build/pg${{ github.event.inputs.pg_version }}/
        docker cp test_pg${{ github.event.inputs.pg_version }}:/src/sql/ dev-build/pg${{ github.event.inputs.pg_version }}/
        
        tar -czf jsonb_merge-dev-pg${{ github.event.inputs.pg_version }}.tar.gz -C dev-build pg${{ github.event.inputs.pg_version }}

    - name: Upload development artifact
      if: github.event.inputs.create_artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: jsonb_merge-dev-pg${{ github.event.inputs.pg_version }}
        path: jsonb_merge-dev-pg${{ github.event.inputs.pg_version }}.tar.gz
        retention-days: 7

    - name: Cleanup
      if: always()
      run: |
        docker rm -f test_pg${{ github.event.inputs.pg_version }} || true
